### ISSUE TITLE
load data error 

### ISSUE THREAD

**Issue by zht3344** [leocvml/deeplabv3plus-gluon-mxnet#1]
read 5046 examples
read 5046 examples
Traceback (most recent call last):
  File "deeplabV3/deeplabv3plus-gluon-mxnet/deeplabv3plus.py", line 286, in <module>
    for d, l in train_iter:
  File "/usr/local/lib/python2.7/dist-packages/mxnet/gluon/data/dataloader.py", line 93, in __iter__
    yield _batchify([self._dataset[idx] for idx in batch])
  File "deeplabV3/deeplabv3plus-gluon-mxnet/deeplabv3plus.py", line 243, in __getitem__
    return data.transpose((2, 0, 1)), self.label_indices(label)
  File "deeplabV3/deeplabv3plus-gluon-mxnet/deeplabv3plus.py", line 195, in label_indices
    return self.colormap2label[idx]
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray/ndarray.py", line 574, in __getitem__
    str(key), str(type(key))))
ValueError: NDArray does not support slicing with key 
[[  32768   32768   32768 ..., 8388608 8388608 8388608]
 [  32768   32768   32768 ..., 8388608 8388608 8388608]
 [  32768   32768   32768 ..., 8388608 8388608 8388608]
 ..., 
 [8388608 8388608 8388608 ..., 8388608 8388608 8388608]
 [8388608 8388608 8388608 ..., 8388608 8388608 8388608]
 [8388608 8388608 8388608 ..., 8388608 8388608 8388608]]
<NDArray 320x480 @cpu(0)> of type <class 'mxnet.ndarray.ndarray.NDArray'>.

**Comment by leocvml** [comment]
hi 
can you run the  sample code smoothly ?
